In [ ]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vansh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
df = pd.read_csv("../data/raw/fake_reviews.csv")
df.head()

,category,rating,label,text_
0,Electronics_5,1.0,CG,Thankfully I bought the Best Buy wireless adap...
1,Pet_Supplies_5,5.0,CG,I will be ordering this again. The quality is ...
2,Electronics_5,5.0,OR,Wow so glad this popped up to rate! I forgot w...
3,Electronics_5,3.0,CG,"Not as good as OEM, but the quality is good.\r..."
4,Movies_and_TV_5,5.0,OR,"Unfortunately, the version sent to me was appa..."

In [ ]:
df.shape
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  800 non-null    str
 1   rating    800 non-null    float64
 2   label     800 non-null    str
 3   text_     800 non-null    str
dtypes: float64(1), str(3)
memory usage: 25.1 KB

category    0
rating      0
label       0
text_       0
dtype: int64

In [ ]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'<.*?>', '', text)  # remove HTML
    text = re.sub(r'[^a-z\s]', '', text)  # remove punctuation
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text

In [17]:
df['cleaned_text'] = df['text_'].apply(clean_text)
df.head()

,category,rating,label,text_,cleaned_text
0,Electronics_5,1.0,CG,Thankfully I bought the Best Buy wireless adap...,thankfully bought best buy wireless adapters r...
1,Pet_Supplies_5,5.0,CG,I will be ordering this again. The quality is ...,ordering quality good really best onei bought ...
2,Electronics_5,5.0,OR,Wow so glad this popped up to rate! I forgot w...,wow glad popped rate forgot liked past year st...
3,Electronics_5,3.0,CG,"Not as good as OEM, but the quality is good.\r...",good oem quality good reason gave
4,Movies_and_TV_5,5.0,OR,"Unfortunately, the version sent to me was appa...",unfortunately version sent apparently european...

In [18]:
df.to_csv("../data/processed/cleaned_reviews.csv", index=False)